// You may write any gradle buildscript component in this file
// This file is automatically applied after build.gradle + dependencies.gradle is ran

// If you wish to use the default helper methods, uncomment the line below
// apply from: 'gradle/scripts/helpers.gradle'
apply plugin: ProjectDefaultsPlugin
apply plugin: FlatBuffersPlugin

evaluationDependsOn ":markdown"

sourceSets {
    testmod {
        compileClasspath += sourceSets.main.output + configurations.compileClasspath
        runtimeClasspath += sourceSets.main.output + configurations.runtimeClasspath
    }
}

unimined.minecraft(sourceSets.testmod) {
    combineWith(sourceSets.main)
    defaultRemapJar = false
    defaultRemapSourcesJar = false
}

tasks.register("printProjectVersion", PrintProjectVersion.class);

def publicApiIncludePatterns = {
    exclude "**/*Internal.*"
    exclude "**/*Internal\$*.*"
    exclude "**/internal/**"
}

javadoc {
    source = sourceSets.main.allJava
    classpath = sourceSets.main.compileClasspath + sourceSets.main.output

    options.addStringOption('Xdoclint:none', '-quiet')
    options.encoding = 'UTF-8'
    options.charSet = 'UTF-8'
}
javadoc publicApiIncludePatterns

tasks.register('apiJar', Jar) {
    archiveClassifier = "api"
    // api jar ist just a development aid and serves as both a binary and source jar simultaneously
    from sourceSets.main.output
    from sourceSets.main.allJava
    from project(":markdown").sourceSets.main.output
    include "**/*.class"
}
apiJar publicApiIncludePatterns

afterEvaluate {
    println('Version: ' + project.version)
}
